services:
  docker-webhook-agent:
    build: .
    container_name: docker-webhook-agent
    restart: always
    ports:
      - "9000:9000"
    environment:
      - PORT=9000
      - SECRET_TOKEN=${WEBHOOK_TOKEN}
    env_file:
      - .env
    volumes:
      # Mount quyền truy cập Docker Daemon từ máy host vào container
      - /var/run/docker.sock:/var/run/docker.sock
      # QUAN TRỌNG: Đường dẫn bên trong và bên ngoài phải giống hệt nhau (DooD)
      - /root/online-study:/root/online-study
    networks:
      - online-study_online-study-network

networks:
  online-study_online-study-network:
    external: true
