upstream frontend_service {
    server online-study-frontend-blue:80;
}

upstream backend_service {
    server online-study-backend-blue:8080;
}

upstream grafana_service {
    server online-study-grafana:3000;
}

upstream prometheus_service {
    server online-study-prometheus:9090;
}
